Step 7 Complete
ggr1992/nc-games pull request #4
Opened 2023-06-01 10:27 UTC by ggr1992

2023-06-01 11:11 UTC, MrMcSnail requested changes
Good work so far! 

The votes for your reviews are not persistent between sessions because you've not made an update to the database. 

Once you've got that working, push your changes to this branch and then resubmit an nchelp pr

2023-06-01 15:15 UTC, MKD01 requested changes
great work so far but there are still a few things to take a look at before merging this in. 

Once you have made those changes please re-submit this as a new pr.

2023-06-01 15:15 UTC, MKD01 commented on src/Components/SingleReview.jsx
>    };
You shouldnt update votes with the new value from the patch request if you are optimistically updating this value already.

2023-06-01 15:15 UTC, MKD01 commented on src/Components/SingleReview.jsx
> -
If this patch request fails for any reason the user should be given some form of visual feedback.

2023-06-02 08:02 UTC, Jodiech approved these changes
Great work! Your votes are now persistent on a refresh 🥳 Happy for you to merge 🚀

2023-06-02 08:19 UTC, merged